### ISSUE TITLE
[1.1] Missing install_requires=['docutils'] ?

### ISSUE THREAD

**Issue by hartwork** [jupyter/sphinxcontrib_github_alt#3]
```console
# cd "$(mktemp -d)"

# virtualenv --python=python3.7 py37
Running virtualenv with interpreter /usr/bin/python3.7
Already using interpreter /usr/bin/python3.7
Using base prefix '/usr'
New python3.7 executable in /tmp/tmp.wrF8nD7QPR/py37/bin/python3.7
Not overwriting existing python3.7 script /tmp/tmp.wrF8nD7QPR/py37/bin/python3.7 (you must use /tmp/tmp.wrF8nD7QPR/py37/bin/python3.7)
Installing setuptools, pip, wheel...
done.

# source py37/bin/activate

# pip install sphinxcontrib_github_alt
Collecting sphinxcontrib_github_alt
  Using cached sphinxcontrib_github_alt-1.1-py2.py3-none-any.whl (8.9 kB)
Installing collected packages: sphinxcontrib-github-alt
Successfully installed sphinxcontrib-github-alt-1.1

# python -c 'import sphinxcontrib_github_alt'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/tmp.wrF8nD7QPR/py37/lib/python3.7/site-packages/sphinxcontrib_github_alt.py", line 18, in <module>
    from docutils import nodes, utils
ModuleNotFoundError: No module named 'docutils'
```

**Comment by hartwork** [comment]
PS: Same for `sphinx`

**Comment by takluyver** [comment]
Sure, that makes sense, I guess. I've never really thought about it, because it's a Sphinx extension, so you're always adding it to an environment which already contains Sphinx & docutils (Sphinx depends on docutils).

Do you want to make a PR? Requirements would go in `pyproject.toml`, and the format details are described here: https://flit.readthedocs.io/en/latest/pyproject_toml.html#metadata-section

**Comment by hartwork** [comment]
I'm up to try, yes. Thanks for the link. I would add docutils as well because it's a direct dependency due to the direct import. Let's see…

**Comment by hartwork** [comment]
I have pull request #4 ready for review now.

**Comment by hartwork** [comment]
@takluyver do you have a minute to review #4?
